<a href="https://colab.research.google.com/github/ce888-sr/CE888_Lab/blob/main/Lab2/bootstrap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook you'll create your own bootstrap function following the bootstrap algorithm (check the lecture notes!)

In [1]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np



In [2]:
# Load the data
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/customers.csv')
data = df.values.T[1]
print(data)

[ 2.  8. 20. 13.  5.  9. 10.  8. 22. 10.  2.  4.  7.  9.]


In [3]:
def bootstrap_mean(x, sample_size, n_bootstraps):
    data_mean = np.empty(sample_size) #create empty array
    sample = np.array([np.random.choice(x, size=sample_size, replace = True) for i in range(n_bootstraps)])
    data_mean = np.mean(sample, axis=1)
    
    ordered = np.sort(data_mean)
    lower = np.percentile(ordered, (1-0.95)/2)
    upper = np.percentile(ordered, 0.95+((1-0.95)/2))
    
    return data_mean, lower, upper

In [4]:
bootstrap_mean(data, len(data), 10000)

(array([10.71428571,  8.28571429,  9.64285714, ...,  9.07142857,
        10.        , 11.21428571]), 4.714250000000001, 6.035017857142858)

In [5]:
def bootstrap_mean_ci(sample, sample_size, n_bootstraps, ci):
    data_mean = np.empty(sample_size) #create empty array
    sample = np.array([np.random.choice(sample, size=sample_size, replace = True) for i in range(n_bootstraps)]) #create bootstraps
    data_mean = np.nanmean(sample, axis=1) # create array of bootstrap means
    
    ordered = np.sort(data_mean) #sort the array of means in ascending order
    lower = np.percentile(ordered, (100-ci)/2) #lower bound of ci alpha
    upper = np.percentile(ordered, ci+((100-ci)/2)) #upper bound of ci alpha
    return data_mean, lower, upper


In [6]:
def bootstrap_stand_ci(sample, sample_size, n_bootstraps, ci):
    data_std = np.empty(sample_size) #create empty array
    sample = np.array([np.random.choice(sample, size=sample_size, replace = True) for i in range(n_bootstraps)]) #create bootstraps
    data_std = np.nanstd(sample, axis=1) # create array of bootstrap means
    
    ordered = np.sort(data_std) #sort the array of means in ascending order
    lower = np.percentile(ordered, (100-ci)/2) #lower bound of ci alpha
    upper = np.percentile(ordered, ci+((100-ci)/2)) #upper bound of ci alpha
    return data_std, lower, upper

In [7]:
bootstrap_mean_ci(data, len(data), 10000, 0.95)

(array([ 9.35714286,  9.57142857, 10.85714286, ...,  8.71428571,
         9.        ,  8.57142857]), 9.142857142857142, 9.142857142857142)

In [8]:
DataFrame = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/vehicles.csv')
#DataFrame.head()
Current_fleet = DataFrame.values.T[0]
New_fleet = DataFrame.values.T[1]

In [9]:
Current_fleet_mean = np.nanmean(Current_fleet)
New_fleet_mean = np.nanmean(New_fleet)

print(Current_fleet_mean, New_fleet_mean)

20.14457831325301 30.481012658227847


In [10]:
bootstrap_mean_ci(Current_fleet, len(Current_fleet), 10000, 99)

(array([19.97188755, 19.85542169, 20.32931727, ..., 20.35742972,
        20.4497992 , 20.5502008 ]), 19.116425702811245, 21.204819277108435)

In [11]:
bootstrap_stand_ci(Current_fleet, len(Current_fleet), 10000, 95)

(array([6.17303697, 6.97860012, 6.28227734, ..., 6.35962257, 6.70559833,
        6.17877196]), 5.801256183322915, 6.951616921292721)

# Vehicles dataset

Now let's work on a different dataset, which is stored in the vehicles.csv file.


In [12]:
# Load and visualise the vehicles dataset
# To load the dataset: https://neptune.ai/blog/google-colab-dealing-with-files (check section "Load individual files directly from GitHub")
DataFrame = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/vehicles.csv')
#DataFrame.head()
Current_fleet = DataFrame.values.T[0]
New_fleet = DataFrame.values.T[1]
New_fleet = New_fleet[~np.isnan(New_fleet)]

# Note that the current and new fleets are in different columns and have different lengths, so bear this in mind when you're plotting.
# You can create separate scatterplots for the two fleets, as you would with the histograms, 
# or plot them both in one plot (but not one against the other).



## Compare the two fleets

The business analysts come up a comparison algorithm that requires the upper and lower bounds for the mean in order to say which fleet is better.
1. Calculate the mean of both samples.
2. Using the bootstrap function that you created:
    - Construct the 95% CI of the mean of the current fleet.
    - Construct the 95% CI of the mean of the new fleet.
    - Are they comparable? (i.e., is one better than the other?) -- you can do this with a permutation test (check the lecture notes!)

In [13]:
Current_fleet_mean = np.nanmean(Current_fleet)
New_fleet_mean = np.nanmean(New_fleet)

print(Current_fleet_mean, New_fleet_mean)

20.14457831325301 30.481012658227847


In [14]:
bootstrap_mean(New_fleet, len(New_fleet), 10000)

(array([30.63291139, 31.13924051, 30.70886076, ..., 29.98734177,
        30.08860759, 31.62025316]), 27.993636075949368, 28.873417721518987)

In [15]:
bootstrap_mean_ci(Current_fleet, len(Current_fleet), 10000, 0.80)

(array([20.57429719, 19.69477912, 19.91164659, ..., 21.        ,
        19.47791165, 19.90763052]), 20.136546184738958, 20.14457831325301)

In [16]:
sample1 = Current_fleet[~np.isnan(Current_fleet)]
sample2 = New_fleet[~np.isnan(New_fleet)]

In [17]:
# Create your own function for a permutation test here (you will need it for the lab quiz!):
from itertools import permutations 
def permut_test(sample1, sample2, n_permutations):
    
    
    xold = bootstrap_mean_ci(sample1, sample1.shape[0], 100, 99)[0]
    xnew = bootstrap_mean_ci(sample2, sample2.shape[0], 100, 99)[0]
      
    tobs = xnew - xold
    concat = np.concatenate((sample1, sample2))
    
    k = 0
    
    for i in range (n_permutations):
        perm = np.random.permutation(concat)
        
        pold = perm[:int(len(perm)/2)]
        pnew = perm[int(len(perm/2)):]
        
        mold = bootstrap_mean_ci(pold, pold.shape[0], 100, 99)[0]
        mnew = bootstrap_mean_ci(pnew, pnew.shape[0], 100, 99)[0]
        
        tperm = abs(mnew - mold)
        if tperm > tobs:
            k += 1
        
    pvalue = k/n_permutations
                             
    """
    sample1: 1D array
    sample2: 1D array (note that the size of the two arrays can be different)
    n_permutations: number of permutations to calculate the p-value
    """
    return pvalue

In [18]:
permut_test(Current_fleet, New_fleet, 3000)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice
  after removing the cwd from sys.path.


ValueError: ignored